version: '3'

services:
    mongo-express:
      image: mongo-express
      ports:
          - 8081:8081
      environment:
          ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
          ME_CONFIG_MONGODB_PORT: 27017
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      links:
            - mongo
      networks:
            - mongodb-network
      depends_on:
            - mongo

    mongo:
      image: mongo
      container_name: monguinho
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
          MONGO_NON_ROOT_USERNAME: user
          MONGO_NON_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: monguito
      ports:
          - 27017:27017
      networks:
          - mongodb-network
      volumes:
          - ./scripts/no-sql-init-db:/docker-entrypoint-initdb.d

    redis:
      image: redis:6.0.6-alpine
      ports:
          - 6379:6379
      environment:
          - HOSTNAME_EXTERNAL=redis

networks:
    mongodb-network:
          driver: bridge